import images from "@/constants/images";
import type { Notification } from "@/utils/Types/notifications";

export const mockNotifications: Notification[] = [
  {
    id: "1",
    type: "booking",
    title: "Booking Confirmed",
    message: "Your booking for Modern Family House has been confirmed for March 15, 2026.",
    time: "2 hours ago",
    isRead: false,
    image: images.newYork,
  },
  {
    id: "2",
    type: "payment",
    title: "Payment Successful",
    message: "Your payment of $2,500 has been processed successfully.",
    time: "5 hours ago",
    isRead: false,
  },
  {
    id: "3",
    type: "alert",
    title: "Price Drop Alert",
    message: "Cozy Apartment price reduced from $1,800 to $1,200. Check it out now!",
    time: "1 day ago",
    isRead: true,
    image: images.berlin,
  },
  {
    id: "4",
    type: "update",
    title: "New Property Match",
    message: "We found 3 new properties matching your search criteria.",
    time: "2 days ago",
    isRead: true,
  },
  {
    id: "5",
    type: "promo",
    title: "Special Offer 🎉",
    message: "Get 20% off on your first booking this weekend only!",
    time: "3 days ago",
    isRead: true,
  },
  {
    id: "6",
    type: "alert",
    title: "Watchlist Update",
    message: "A property from your watchlist is now available for viewing.",
    time: "4 days ago",
    isRead: true,
  },
  {
    id: "7",
    type: "booking",
    title: "Booking Reminder",
    message: "Your property viewing is scheduled for tomorrow at 2:00 PM.",
    time: "5 days ago",
    isRead: true,
    image: images.dubai,
  },
  {
    id: "8",
    type: "payment",
    title: "Refund Processed",
    message: "Your refund of $1,200 has been initiated and will arrive in 3-5 business days.",
    time: "6 days ago",
    isRead: true,
  },
  {
    id: "9",
    type: "alert",
    title: "New Review",
    message: "Someone left a review on a property you viewed.",
    time: "1 week ago",
    isRead: true,
    image: images.japan,
  },
  {
    id: "10",
    type: "update",
    title: "Search Saved",
    message: "Your search criteria has been saved successfully.",
    time: "1 week ago",
    isRead: true,
  },
  {
    id: "11",
    type: "promo",
    title: "Refer a Friend",
    message: "Invite friends and earn $50 credit for each successful booking!",
    time: "1 week ago",
    isRead: true,
  },
  {
    id: "12",
    type: "booking",
    title: "Booking Cancelled",
    message: "Your booking has been cancelled as per your request.",
    time: "2 weeks ago",
    isRead: true,
  },
  {
    id: "13",
    type: "payment",
    title: "Payment Method Added",
    message: "New payment method ending in 4242 has been added to your account.",
    time: "2 weeks ago",
    isRead: true,
  },
  {
    id: "14",
    type: "alert",
    title: "Property Available",
    message: "Luxury Villa is now available for booking on your preferred dates.",
    time: "2 weeks ago",
    isRead: true,
    image: images.maldives,
  },
  {
    id: "15",
    type: "update",
    title: "Profile Updated",
    message: "Your profile information has been updated successfully.",
    time: "3 weeks ago",
    isRead: true,
  },
  {
    id: "16",
    type: "booking",
    title: "Booking Request",
    message: "New booking request received for your property listing.",
    time: "3 weeks ago",
    isRead: true,
    image: images.newYork,
  },
  {
    id: "17",
    type: "payment",
    title: "Monthly Statement",
    message: "Your monthly payment statement is now available for download.",
    time: "1 month ago",
    isRead: true,
  },
  {
    id: "18",
    type: "alert",
    title: "Maintenance Alert",
    message: "Scheduled maintenance on March 20th from 2:00 AM to 4:00 AM.",
    time: "1 month ago",
    isRead: true,
  },
  {
    id: "19",
    type: "update",
    title: "App Update Available",
    message: "Version 2.5.0 is available with new features and improvements.",
    time: "1 month ago",
    isRead: true,
  },
  {
    id: "20",
    type: "promo",
    title: "Summer Special",
    message: "Book properties for summer and get up to 30% discount!",
    time: "1 month ago",
    isRead: true,
  },
  {
    id: "21",
    type: "booking",
    title: "Check-in Reminder",
    message: "Don't forget to check-in for your upcoming property visit.",
    time: "1 month ago",
    isRead: true,
    image: images.berlin,
  },
  {
    id: "22",
    type: "payment",
    title: "Payment Reminder",
    message: "Your payment is due in 3 days. Please ensure sufficient balance.",
    time: "1 month ago",
    isRead: true,
  },
  {
    id: "23",
    type: "alert",
    title: "Security Alert",
    message: "New login detected from a different device. Was this you?",
    time: "2 months ago",
    isRead: true,
  },
  {
    id: "24",
    type: "update",
    title: "Policy Update",
    message: "Our terms and conditions have been updated. Please review.",
    time: "2 months ago",
    isRead: true,
  },
  {
    id: "25",
    type: "promo",
    title: "Birthday Special",
    message: "Happy Birthday! Enjoy 15% off on your next booking as our gift.",
    time: "2 months ago",
    isRead: true,
  },
  {
    id: "26",
    type: "booking",
    title: "Booking Expired",
    message: "Your booking request has expired due to no response from the host.",
    time: "2 months ago",
    isRead: true,
    image: images.dubai,
  },
  {
    id: "27",
    type: "payment",
    title: "Annual Report",
    message: "Your annual transaction report is ready for download.",
    time: "2 months ago",
    isRead: true,
  },
  {
    id: "28",
    type: "alert",
    title: "Property Removed",
    message: "A property from your watchlist has been removed by the owner.",
    time: "2 months ago",
    isRead: true,
  },
  {
    id: "29",
    type: "update",
    title: "New Features",
    message: "Check out our new 360° virtual tour feature for properties!",
    time: "3 months ago",
    isRead: true,
  },
  {
    id: "30",
    type: "promo",
    title: "Flash Sale",
    message: "24-hour flash sale! Up to 50% off on selected properties.",
    time: "3 months ago",
    isRead: true,
  },
];
